# Generated by Django 4.2.7 on 2024-07-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('short_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Politics'), (2, 'India'), (3, 'World'), (4, 'Sports'), (5, 'Health'), (6, 'Science & Tech.'), (7, 'Finance'), (8, 'Education'), (9, 'Listyle'), (10, 'Weather'), (11, 'Entertainment'), (12, 'Travel'), (13, 'Crime')], default=0)),
            ],
        ),
    ]
