# Generated by Django 4.2.7 on 2024-07-15 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='news_img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
